package modelo.entidad;
// Generated 24/09/2023 11:39:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer id;
     private Departamentos departamentos;
     private String documentoTipo;
     private String documentoNumero;
     private String nombres;
     private String apellidos;
     private String ciudad;
     private String direccion;
     private String correoElectronico;
     private String telefono;
     private Date fechaHoraCreacion;
     private Date fechaHoraModifica;

    public Empleados() {
    }

    public Empleados(Departamentos departamentos, String documentoTipo, String documentoNumero, String nombres, String apellidos, String ciudad, String direccion, String correoElectronico, String telefono, Date fechaHoraCreacion, Date fechaHoraModifica) {
       this.departamentos = departamentos;
       this.documentoTipo = documentoTipo;
       this.documentoNumero = documentoNumero;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.fechaHoraCreacion = fechaHoraCreacion;
       this.fechaHoraModifica = fechaHoraModifica;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getDocumentoTipo() {
        return this.documentoTipo;
    }
    
    public void setDocumentoTipo(String documentoTipo) {
        this.documentoTipo = documentoTipo;
    }
    public String getDocumentoNumero() {
        return this.documentoNumero;
    }
    
    public void setDocumentoNumero(String documentoNumero) {
        this.documentoNumero = documentoNumero;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaHoraCreacion() {
        return this.fechaHoraCreacion;
    }
    
    public void setFechaHoraCreacion(Date fechaHoraCreacion) {
        this.fechaHoraCreacion = fechaHoraCreacion;
    }
    public Date getFechaHoraModifica() {
        return this.fechaHoraModifica;
    }
    
    public void setFechaHoraModifica(Date fechaHoraModifica) {
        this.fechaHoraModifica = fechaHoraModifica;
    }




}


